# Generated by Django 4.1 on 2023-09-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('corpus_id', models.IntegerField()),
                ('incipit', models.CharField(max_length=255)),
                ('cantus_id', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('finalis', models.CharField(max_length=255)),
                ('differentia', models.CharField(max_length=255)),
                ('siglum', models.CharField(max_length=255)),
                ('folio', models.CharField(max_length=255)),
                ('sequence', models.CharField(max_length=255)),
                ('marginalia', models.CharField(max_length=255)),
                ('cao_concordances', models.CharField(max_length=255)),
                ('feast_id', models.CharField(max_length=255)),
                ('genre_id', models.CharField(max_length=255)),
                ('office_id', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('melody_id', models.CharField(max_length=255)),
                ('drupal_path', models.CharField(max_length=255)),
                ('full_text', models.CharField(max_length=65025)),
                ('full_text_manuscript', models.CharField(max_length=65025)),
                ('volpiano', models.CharField(max_length=65025)),
                ('notes', models.CharField(max_length=65025)),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_idx', models.IntegerField()),
                ('image_link', models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('siglum', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=65025)),
                ('rism', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('century', models.CharField(max_length=255)),
                ('provenance', models.CharField(max_length=255)),
                ('provenance_detail', models.CharField(max_length=255)),
                ('segment', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=65025)),
                ('indexing_notes', models.CharField(max_length=65025)),
                ('liturgical_occasions', models.CharField(max_length=65025)),
                ('indexing_date', models.CharField(max_length=255)),
                ('drupal_path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cursus', models.CharField(max_length=255)),
                ('image_link', models.CharField(max_length=511)),
                ('n_cantus_chants', models.IntegerField()),
                ('n_cantus_melodies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Melody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volpiano', models.CharField(max_length=65025)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenomelEditor.chant')),
            ],
        ),
    ]
