# Generated by Django 4.1 on 2023-09-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenomelEditor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
