# Generated by Django 4.1 on 2023-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenomelEditor', '0003_chant_position_melody_user_alter_chant_cantus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melody',
            name='is_adiastematic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='century',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='cursus',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.CharField(default=None, max_length=65025, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='image_link',
            field=models.CharField(default=None, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='indexing_date',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='indexing_notes',
            field=models.CharField(default=None, max_length=65025, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='liturgical_occasions',
            field=models.CharField(default=None, max_length=65025, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='n_cantus_chants',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='n_cantus_melodies',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='provenance',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='provenance_detail',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='rism',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='segment',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='siglum',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='summary',
            field=models.CharField(default=None, max_length=65025, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
