# Generated by Django 4.1 on 2023-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenomelEditor', '0004_melody_is_adiastematic_alter_source_century_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melody',
            name='is_in_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melody',
            name='is_in_transcription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melody',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
