# Generated by Django 4.1 on 2023-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenomelEditor', '0005_melody_is_in_checks_melody_is_in_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melody',
            name='syllabized_text',
            field=models.CharField(default=None, max_length=65025, null=True),
        ),
    ]
