# Generated by Django 4.1 on 2023-09-08 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GenomelEditor', '0006_melody_syllabized_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melody',
            name='user',
        ),
        migrations.AddField(
            model_name='melody',
            name='user_checker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='melody',
            name='user_transcriber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='transcriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='melody',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
