# Generated by Django 4.1 on 2023-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenomelEditor', '0007_remove_melody_user_melody_user_checker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='melody',
            old_name='is_submitted',
            new_name='is_finalized',
        ),
        migrations.AddField(
            model_name='melody',
            name='is_incomplete_in_source',
            field=models.BooleanField(default=False),
        ),
    ]
